# Generated by Django 2.1.2 on 2018-12-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ascensor',
            fields=[
                ('id_asc', models.CharField(editable=False, help_text='Id unico por ascensor', max_length=12, primary_key=True, serialize=False, verbose_name='ID del ascensor')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAsc',
            fields=[
                ('id_mo', models.CharField(editable=False, help_text='ID único para el modelo de ascensor.', max_length=12, primary_key=True, serialize=False, verbose_name='ID Modelo')),
                ('nom_modasc', models.CharField(help_text='Nombre del modelo.', max_length=200, verbose_name='Nombre del Modelo')),
            ],
        ),
        migrations.AddField(
            model_name='ascensor',
            name='mod_asc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ascensor.ModelAsc'),
        ),
    ]
