# Generated by Django 2.1.2 on 2018-12-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascensor',
            name='id_asc',
            field=models.CharField(help_text='Id unico por ascensor', max_length=12, primary_key=True, serialize=False, verbose_name='ID del ascensor'),
        ),
        migrations.AlterField(
            model_name='modelasc',
            name='id_mo',
            field=models.CharField(help_text='ID único para el modelo de ascensor.', max_length=12, primary_key=True, serialize=False, verbose_name='ID Modelo'),
        ),
    ]
