# Generated by Django 2.1.2 on 2018-12-14 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ascensor', '0001_initial'),
        ('cliente', '0003_auto_20181214_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('folio', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de orden')),
                ('hr_in', models.TimeField(verbose_name='Hora Inicio')),
                ('hr_tr', models.TimeField(null=True, verbose_name='Hora Termino')),
                ('fails', models.TextField(null=True, verbose_name='Fallas detectadas')),
                ('rep', models.TextField(null=True, verbose_name='Reparaciones efectuadas')),
                ('pi_ch', models.TextField(null=True, verbose_name='Piezas cambiadas')),
                ('nom_rec', models.CharField(max_length=50, null=True, verbose_name='Nombre de quien recibe trabajo')),
                ('fk_asc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ascensor.Ascensor', verbose_name='Ascensor a trabajar')),
                ('fk_cli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='Cliente a atender')),
                ('fk_tec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tecnico que atiende')),
            ],
        ),
    ]
