# Generated by Django 2.1.2 on 2018-12-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='folio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
