# Generated by Django 2.1.2 on 2018-12-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ci', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nom_ci', models.CharField(max_length=100, verbose_name='Nombre Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.CharField(editable=False, help_text='ID único para el Cliente', max_length=12, primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('nom_cli', models.CharField(help_text='Nombre completo del Cliente', max_length=200, verbose_name='Nombre Cliente')),
                ('dir_cli', models.CharField(help_text='Dirección de Cliente', max_length=150, verbose_name='Dirección del Cliente')),
                ('fon_cli', models.CharField(help_text='Número de telefono de contacto Cliente', max_length=13, verbose_name='Número de contacto Cliente')),
                ('cor_cli', models.EmailField(max_length=254)),
                ('ci_cli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_co', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nom_co', models.CharField(max_length=100, verbose_name='Nombre Comuna')),
                ('fk_ci', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='co_cli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Comuna'),
        ),
    ]
