# Generated by Django 2.1.2 on 2018-12-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='fk_ci',
        ),
        migrations.AddField(
            model_name='comuna',
            name='fk_ci',
            field=models.ManyToManyField(to='cliente.Ciudad', verbose_name='Región/Ciudad'),
        ),
    ]
