# Generated by Django 2.1.2 on 2018-12-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20181214_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='id_ci',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cli',
            field=models.CharField(help_text='ID único para el Cliente', max_length=12, primary_key=True, serialize=False, verbose_name='ID Cliente'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='id_co',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
