# Generated by Django 2.1.2 on 2018-12-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignar',
            fields=[
                ('id_as', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('fk_cli', models.ForeignKey(help_text='Cliente que pidio orden', null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='Cliente Asignado')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tec', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nom_tec', models.CharField(help_text='Nombre completo del tecnico', max_length=150, verbose_name='Nombre completo')),
                ('em_tec', models.EmailField(help_text='Email del tecnico', max_length=254, verbose_name='Email (usuario)')),
                ('pw_tec', models.CharField(help_text='Contraseña de ingreso', max_length=20, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asignar',
            name='fk_tec',
            field=models.ForeignKey(help_text='Tecnico que se le asignara Cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Tecnico', verbose_name='Tecnico a Asignar'),
        ),
    ]
